CREATE TABLE  "ARTIKEL" 
   (	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"TITEL" VARCHAR2(400) NOT NULL ENABLE, 
	"TYP" VARCHAR2(12) NOT NULL ENABLE, 
	 CONSTRAINT "ARTIKEL_PK" PRIMARY KEY ("ARTIKEL_ID") ENABLE, 
	 CONSTRAINT "ARTIKEL_CK1" CHECK (TYP IN ('SEITE','TERMIN')) ENABLE
   )
/
CREATE TABLE  "BENUTZER" 
   (	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(400) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(400) NOT NULL ENABLE, 
	"ANZEIGENAME" VARCHAR2(400) NOT NULL ENABLE, 
	"AKTIV" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BENUTZER_PK" PRIMARY KEY ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "BENUTZER_CK1" CHECK (aktiv IN (0,1) ) ENABLE
   )
/
CREATE TABLE  "ARTIKELVERSION" 
   (	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"ERSTELLUNGSDATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"AENDERUNGSDATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"ERSCHEINUNGSDATUM" TIMESTAMP (6), 
	"ABLAUFDATUM" TIMESTAMP (6), 
	"MARKUPTEXT" CLOB, 
	"ANZEIGETEXT" CLOB, 
	"STATUS" VARCHAR2(400) NOT NULL ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_PK" PRIMARY KEY ("ARTIKELVERSION_ID") ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_CK1" CHECK (STATUS IN ('Entwurf','Veroeffentlicht','Archiv') ) ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_FK2" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_FK" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES  "ARTIKEL" ("ARTIKEL_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "MENUBAUM" 
   (	"MENUBAUM_ID" NUMBER NOT NULL ENABLE, 
	"TITEL" VARCHAR2(4000) NOT NULL ENABLE, 
	"GEWICHT" NUMBER NOT NULL ENABLE, 
	"PARENT_MENUBAUM_ID" NUMBER, 
	 CONSTRAINT "MENUBAUM_PK" PRIMARY KEY ("MENUBAUM_ID") ENABLE, 
	 CONSTRAINT "MENUBAUM_CON" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE
   )
/
CREATE TABLE  "ROLLE" 
   (	"ROLLE_ID" NUMBER NOT NULL ENABLE, 
	"BEZEICHNUNG" VARCHAR2(400) NOT NULL ENABLE, 
	"MENUBAUM_ID" NUMBER, 
	 CONSTRAINT "ROLLE_PK" PRIMARY KEY ("ROLLE_ID") ENABLE, 
	 CONSTRAINT "ROLLE_FK" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE
   )
/
CREATE TABLE  "BENUTZER_ROLLE" 
   (	"BENUTZER_ID" NUMBER, 
	"ROLLE_ID" NUMBER, 
	 CONSTRAINT "BENUTZER_ROLLE_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "BENUTZER_ROLLE_FK2" FOREIGN KEY ("ROLLE_ID")
	  REFERENCES  "ROLLE" ("ROLLE_ID") ENABLE
   )
/
CREATE TABLE  "MEDIEN" 
   (	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	"PFAD" VARCHAR2(4000) NOT NULL ENABLE, 
	"TITEL" VARCHAR2(400) NOT NULL ENABLE, 
	"BESCHREIBUNG" VARCHAR2(4000), 
	"TYP" VARCHAR2(4000) NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MEDIEN_PK" PRIMARY KEY ("MEDIEN_ID") ENABLE, 
	 CONSTRAINT "MEDIEN_CK1" CHECK (typ IN ('Bild','Audio','Dokument') ) ENABLE, 
	 CONSTRAINT "MEDIEN_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE
   )
/
CREATE TABLE  "MEDIEN_ARTIKELVERSION" 
   (	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MEDIEN_ARTIKEL_FK" FOREIGN KEY ("MEDIEN_ID")
	  REFERENCES  "MEDIEN" ("MEDIEN_ID") ENABLE, 
	 CONSTRAINT "MEDIEN_ARTIKEL_FK2" FOREIGN KEY ("ARTIKELVERSION_ID")
	  REFERENCES  "ARTIKELVERSION" ("ARTIKELVERSION_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "MENUARTIKEL" 
   (	"MENUBAUM_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"GEWICHT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MENUARTIKEL_FK" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE, 
	 CONSTRAINT "MENUARTIKEL_FK2" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES  "ARTIKEL" ("ARTIKEL_ID") ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"SCHLAGWORT" VARCHAR2(400) NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_PK" PRIMARY KEY ("SCHLAGWORT_ID") ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT_ARTIKELVERSION" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_ARTIKELVERSION_FK" FOREIGN KEY ("SCHLAGWORT_ID")
	  REFERENCES  "SCHLAGWORT" ("SCHLAGWORT_ID") ENABLE, 
	 CONSTRAINT "SCHLAGWORT_ARTIKELVERSION_FK2" FOREIGN KEY ("ARTIKELVERSION_ID")
	  REFERENCES  "ARTIKELVERSION" ("ARTIKELVERSION_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT_MEDIEN" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_MEDIEN_FK" FOREIGN KEY ("SCHLAGWORT_ID")
	  REFERENCES  "SCHLAGWORT" ("SCHLAGWORT_ID") ENABLE, 
	 CONSTRAINT "SCHLAGWORT_MEDIEN_FK2" FOREIGN KEY ("MEDIEN_ID")
	  REFERENCES  "MEDIEN" ("MEDIEN_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "SPERRE" 
   (	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"ZEITSTEMPEL" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "SPERRE_PK" PRIMARY KEY ("ARTIKELVERSION_ID") ENABLE, 
	 CONSTRAINT "SPERRE_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ON DELETE CASCADE ENABLE
   )
/

 CREATE SEQUENCE   "ARTIKELVERSION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ARTIKEL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "BENUTZER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MEDIEN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MENUBAUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ROLLE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "SCHLAGWORT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER  "BI_ARTIKEL" 
  before insert on "ARTIKEL"               
  for each row  
begin   
    select "ARTIKEL_SEQ".nextval into :NEW.ARTIKEL_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ARTIKEL" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ARTIKELVERSION" 
  before insert on "ARTIKELVERSION"               
  for each row  
begin   
    select "ARTIKELVERSION_SEQ".nextval into :NEW.ARTIKELVERSION_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ARTIKELVERSION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_BENUTZER" 
  before insert on "BENUTZER"               
  for each row  
begin   
    select "BENUTZER_SEQ".nextval into :NEW.BENUTZER_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_BENUTZER" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MEDIEN" 
  before insert on "MEDIEN"               
  for each row  
begin   
    select "MEDIEN_SEQ".nextval into :NEW.MEDIEN_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MEDIEN" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MENUBAUM" 
  before insert on "MENUBAUM"               
  for each row  
begin   
    select "MENUBAUM_SEQ".nextval into :NEW.MENUBAUM_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MENUBAUM" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ROLLE" 
  before insert on "ROLLE"               
  for each row  
begin   
    select "ROLLE_SEQ".nextval into :NEW.ROLLE_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ROLLE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_SCHLAGWORT" 
  before insert on "SCHLAGWORT"               
  for each row  
begin   
    select "SCHLAGWORT_SEQ".nextval into :NEW.SCHLAGWORT_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_SCHLAGWORT" ENABLE
/
