DROP TRIGGER  "BI_SCHLAGWORT"
/
DROP TRIGGER "BI_ROLLE"
/
DROP TRIGGER "BI_MENUBAUM"
/
DROP TRIGGER "BI_BENUTZER"
/
DROP TRIGGER "BI_ARTIKELVERSION"
/
DROP TRIGGER "BI_ARTIKEL"
/
DROP SEQUENCE "SCHLAGWORT_SEQ"
/
DROP SEQUENCE "ROLLE_SEQ"
/
DROP SEQUENCE "MENUBAUM_SEQ" 
/
DROP SEQUENCE "MEDIEN_SEQ" 
/
DROP SEQUENCE "BENUTZER_SEQ" 
/
DROP SEQUENCE "ARTIKEL_SEQ"
/
DROP SEQUENCE "ARTIKELVERSION_SEQ"
/
DROP TABLE KURSE_MARKUPS
/
DROP TABLE MITARBEITER_MARKUPS
/
DROP TABLE LEHRGEBIETE_MARKUPS
/
DROP TABLE FAKULTAETEN_MARKUPS
/
DROP TABLE RAEUME_MARKUPS
/
DROP TABLE GEBAEUDE_MARKUPS
/
DROP TABLE KURSE
/
ALTER TABLE LEHRGEBIETE DROP CONSTRAINT LEHRGEBIET_MITARBEITER_FK
/
DROP TABLE MITARBEITER
/
DROP TABLE LEHRGEBIETE
/
DROP TABLE INSTITUTE
/
DROP TABLE FAKULTAETEN
/
DROP TABLE RAEUME
/
DROP TABLE GEBAEUDE
/
DROP TABLE MARKUPUPDATE
/
DROP TABLE  MARKUPS
/
DROP TABLE  "SPERRE" 
/
DROP TABLE  "SCHLAGWORT_MEDIEN" 
/
DROP TABLE  "SCHLAGWORT_ARTIKELVERSION" 
/
DROP TABLE  "SCHLAGWORT" 
/
DROP TABLE  "MENUARTIKEL" 
/
DROP TABLE  "MEDIEN_ARTIKELVERSION" 
/
DROP TABLE  "MEDIEN" 
/
DROP TABLE  "BENUTZER_ROLLE" 
/
DROP TABLE  "ROLLE" 
/
DROP TABLE  "MENUBAUM" 
/
DROP TABLE  "ARTIKELVERSION" 
/
DROP TABLE  "BENUTZER" 
/
DROP TABLE  "ARTIKEL" 
/
