
ALTER TABLE KURSE_MARKUPS modify CONSTRAINT KURSE_MUPS_KURSE_FK disable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_MITARBEITER_FK disable;
ALTER TABLE MITARBEITER_MARKUPS modify CONSTRAINT MIT_MUPS_MIT_FK disable;
ALTER TABLE MITARBEITER modify CONSTRAINT MIT_LEHRGEBIET_FK disable;
ALTER TABLE LEHRGEBIETE_MARKUPS modify CONSTRAINT LGEB_MUPS_LEHRGEBIETE_FK
disable;
ALTER TABLE KURSE modify CONSTRAINT KURS_LEHRGEBIET_FK disable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_FAKULTAET_FK disable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_INST_FK disable;
ALTER TABLE FAKULTAETEN_MARKUPS modify CONSTRAINT FAK_MUPS_FAK_FK disable;
ALTER TABLE MITARBEITER modify CONSTRAINT MIT_RAUM_FK disable;
ALTER TABLE RAEUME_MARKUPS modify CONSTRAINT RAEUME_MUPS_RAEUME_FK disable;
ALTER TABLE RAEUME  modify CONSTRAINT RAEUME_GEBAEUDE_FK disable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_GEBAEUDE_FK disable;
ALTER TABLE GEBAEUDE_MARKUPS modify CONSTRAINT GEBAEUDE_MUPS_GEBAEUDE_FK
disable;
ALTER TABLE INSTITUTE modify CONSTRAINT INST_FAK_FK disable;
ALTER TABLE RAEUME_MARKUPS modify CONSTRAINT RAEUME_MUPS_MUPS_FK disable;
ALTER TABLE FAKULTAETEN_MARKUPS modify CONSTRAINT FAK_MUPS_MUPS_FK
disable;
ALTER TABLE LEHRGEBIETE_MARKUPS modify CONSTRAINT LGEB_MUPS_MUPS_FK
disable;
ALTER TABLE MITARBEITER_MARKUPS modify CONSTRAINT MIT_MUPS_MUPS_FK disable;
ALTER TABLE KURSE_MARKUPS modify CONSTRAINT KURSE_MUPS_MUPS_FK disable;
ALTER TABLE MARKUPUPDATE modify CONSTRAINT  MARKUPUPDATE_MARKUP_FK disable;
ALTER TABLE GEBAEUDE_MARKUPS modify CONSTRAINT GEBAEUDE_MUPS_MUPS_FK disable;
TRUNCATE TABLE KURSE_MARKUPS
/
TRUNCATE TABLE MITARBEITER_MARKUPS
/
TRUNCATE TABLE LEHRGEBIETE_MARKUPS
/
TRUNCATE TABLE FAKULTAETEN_MARKUPS
/
TRUNCATE TABLE RAEUME_MARKUPS
/
TRUNCATE TABLE GEBAEUDE_MARKUPS
/
TRUNCATE TABLE INSTITUTE
/
TRUNCATE TABLE KURSE
/
TRUNCATE TABLE MITARBEITER
/
TRUNCATE TABLE LEHRGEBIETE
/
TRUNCATE TABLE FAKULTAETEN
/
TRUNCATE TABLE RAEUME
/
TRUNCATE TABLE GEBAEUDE
/
TRUNCATE TABLE MARKUPUPDATE
/
TRUNCATE TABLE  MARKUPS
/
ALTER TABLE KURSE modify CONSTRAINT KURS_LEHRGEBIET_FK enable;
ALTER TABLE KURSE_MARKUPS modify CONSTRAINT KURSE_MUPS_KURSE_FK enable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_MITARBEITER_FK enable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_INST_FK enable;
ALTER TABLE MITARBEITER_MARKUPS modify CONSTRAINT MIT_MUPS_MIT_FK enable;
ALTER TABLE MITARBEITER modify CONSTRAINT MIT_LEHRGEBIET_FK enable;
ALTER TABLE LEHRGEBIETE_MARKUPS modify CONSTRAINT LGEB_MUPS_LEHRGEBIETE_FK
enable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_FAKULTAET_FK enable;
ALTER TABLE FAKULTAETEN_MARKUPS modify CONSTRAINT FAK_MUPS_FAK_FK enable;
ALTER TABLE MITARBEITER modify CONSTRAINT MIT_RAUM_FK enable;
ALTER TABLE RAEUME_MARKUPS modify CONSTRAINT RAEUME_MUPS_RAEUME_FK enable;
ALTER TABLE RAEUME  modify CONSTRAINT RAEUME_GEBAEUDE_FK enable;
ALTER TABLE LEHRGEBIETE modify CONSTRAINT LEHRGEBIET_GEBAEUDE_FK enable;
ALTER TABLE GEBAEUDE_MARKUPS modify CONSTRAINT GEBAEUDE_MUPS_GEBAEUDE_FK
enable;
ALTER TABLE INSTITUTE modify CONSTRAINT INST_FAK_FK enable;
ALTER TABLE RAEUME_MARKUPS modify CONSTRAINT RAEUME_MUPS_MUPS_FK enable;
ALTER TABLE FAKULTAETEN_MARKUPS modify CONSTRAINT FAK_MUPS_MUPS_FK
enable;
ALTER TABLE LEHRGEBIETE_MARKUPS modify CONSTRAINT LGEB_MUPS_MUPS_FK
enable;
ALTER TABLE MITARBEITER_MARKUPS modify CONSTRAINT MIT_MUPS_MUPS_FK enable;
ALTER TABLE KURSE_MARKUPS modify CONSTRAINT KURSE_MUPS_MUPS_FK enable;
ALTER TABLE MARKUPUPDATE modify CONSTRAINT  MARKUPUPDATE_MARKUP_FK enable;
ALTER TABLE GEBAEUDE_MARKUPS modify CONSTRAINT GEBAEUDE_MUPS_MUPS_FK enable;
