CREATE TABLE  "ARTIKEL" 
   (	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"TITEL" VARCHAR2(400) NOT NULL ENABLE, 
	"TYP" VARCHAR2(12) NOT NULL ENABLE, 
	 CONSTRAINT "ARTIKEL_PK" PRIMARY KEY ("ARTIKEL_ID") ENABLE, 
	 CONSTRAINT "ARTIKEL_CK1" CHECK (TYP IN ('SEITE','TERMIN')) ENABLE
   )
/
CREATE TABLE  "BENUTZER" 
   (	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(400) NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(400) NOT NULL ENABLE, 
	"ANZEIGENAME" VARCHAR2(400) NOT NULL ENABLE, 
	"AKTIV" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BENUTZER_PK" PRIMARY KEY ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "BENUTZER_CK1" CHECK (aktiv IN (0,1) ) ENABLE
   )
/
CREATE TABLE  "ARTIKELVERSION" 
   (	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"ERSTELLUNGSDATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"AENDERUNGSDATUM" TIMESTAMP (6) NOT NULL ENABLE, 
	"ERSCHEINUNGSDATUM" TIMESTAMP (6), 
	"ABLAUFDATUM" TIMESTAMP (6), 
	"MARKUPTEXT" CLOB, 
	"ANZEIGETEXT" CLOB, 
	"STATUS" VARCHAR2(400) NOT NULL ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_PK" PRIMARY KEY ("ARTIKELVERSION_ID") ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_CK1" CHECK (STATUS IN ('Entwurf','Veroeffentlicht','Archiv') ) ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_FK2" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "ARTIKELVERSION_FK" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES  "ARTIKEL" ("ARTIKEL_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "MENUBAUM" 
   (	"MENUBAUM_ID" NUMBER NOT NULL ENABLE, 
	"TITEL" VARCHAR2(4000) NOT NULL ENABLE, 
	"GEWICHT" NUMBER NOT NULL ENABLE, 
	"PARENT_MENUBAUM_ID" NUMBER, 
	 CONSTRAINT "MENUBAUM_PK" PRIMARY KEY ("MENUBAUM_ID") ENABLE, 
	 CONSTRAINT "MENUBAUM_CON" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE
   )
/
CREATE TABLE  "ROLLE" 
   (	"ROLLE_ID" NUMBER NOT NULL ENABLE, 
	"BEZEICHNUNG" VARCHAR2(400) NOT NULL ENABLE, 
	"MENUBAUM_ID" NUMBER, 
	 CONSTRAINT "ROLLE_PK" PRIMARY KEY ("ROLLE_ID") ENABLE, 
	 CONSTRAINT "ROLLE_FK" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE
   )
/
CREATE TABLE  "BENUTZER_ROLLE" 
   (	"BENUTZER_ID" NUMBER, 
	"ROLLE_ID" NUMBER, 
	 CONSTRAINT "BENUTZER_ROLLE_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE, 
	 CONSTRAINT "BENUTZER_ROLLE_FK2" FOREIGN KEY ("ROLLE_ID")
	  REFERENCES  "ROLLE" ("ROLLE_ID") ENABLE
   )
/
CREATE TABLE  "MEDIEN" 
   (	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	"PFAD" VARCHAR2(4000) NOT NULL ENABLE, 
	"TITEL" VARCHAR2(400) NOT NULL ENABLE, 
	"BESCHREIBUNG" VARCHAR2(4000), 
	"TYP" VARCHAR2(4000) NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MEDIEN_PK" PRIMARY KEY ("MEDIEN_ID") ENABLE, 
	 CONSTRAINT "MEDIEN_CK1" CHECK (typ IN ('Bild','Audio','Dokument') ) ENABLE, 
	 CONSTRAINT "MEDIEN_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ENABLE
   )
/
CREATE TABLE  "MEDIEN_ARTIKELVERSION" 
   (	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MEDIEN_ARTIKEL_FK" FOREIGN KEY ("MEDIEN_ID")
	  REFERENCES  "MEDIEN" ("MEDIEN_ID") ENABLE, 
	 CONSTRAINT "MEDIEN_ARTIKEL_FK2" FOREIGN KEY ("ARTIKELVERSION_ID")
	  REFERENCES  "ARTIKELVERSION" ("ARTIKELVERSION_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "MENUARTIKEL" 
   (	"MENUBAUM_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKEL_ID" NUMBER NOT NULL ENABLE, 
	"GEWICHT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MENUARTIKEL_FK" FOREIGN KEY ("MENUBAUM_ID")
	  REFERENCES  "MENUBAUM" ("MENUBAUM_ID") ENABLE, 
	 CONSTRAINT "MENUARTIKEL_FK2" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES  "ARTIKEL" ("ARTIKEL_ID") ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"SCHLAGWORT" VARCHAR2(400) NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_PK" PRIMARY KEY ("SCHLAGWORT_ID") ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT_ARTIKELVERSION" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_ARTIKELVERSION_FK" FOREIGN KEY ("SCHLAGWORT_ID")
	  REFERENCES  "SCHLAGWORT" ("SCHLAGWORT_ID") ENABLE, 
	 CONSTRAINT "SCHLAGWORT_ARTIKELVERSION_FK2" FOREIGN KEY ("ARTIKELVERSION_ID")
	  REFERENCES  "ARTIKELVERSION" ("ARTIKELVERSION_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "SCHLAGWORT_MEDIEN" 
   (	"SCHLAGWORT_ID" NUMBER NOT NULL ENABLE, 
	"MEDIEN_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "SCHLAGWORT_MEDIEN_FK" FOREIGN KEY ("SCHLAGWORT_ID")
	  REFERENCES  "SCHLAGWORT" ("SCHLAGWORT_ID") ENABLE, 
	 CONSTRAINT "SCHLAGWORT_MEDIEN_FK2" FOREIGN KEY ("MEDIEN_ID")
	  REFERENCES  "MEDIEN" ("MEDIEN_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE  "SPERRE" 
   (	"ARTIKELVERSION_ID" NUMBER NOT NULL ENABLE, 
	"BENUTZER_ID" NUMBER NOT NULL ENABLE, 
	"ZEITSTEMPEL" TIMESTAMP (6) NOT NULL ENABLE, 
	 CONSTRAINT "SPERRE_PK" PRIMARY KEY ("ARTIKELVERSION_ID") ENABLE, 
	 CONSTRAINT "SPERRE_FK" FOREIGN KEY ("BENUTZER_ID")
	  REFERENCES  "BENUTZER" ("BENUTZER_ID") ON DELETE CASCADE ENABLE
   )
/
CREATE TABLE Markups 
(
  MARKUP_ID NUMBER NOT NULL,
  TYP VARCHAR(32) NOT NULL,
  CONSTRAINT MUPS_PK PRIMARY KEY (MARKUP_ID) ,
  CONSTRAINT MUPS_CK CHECK (TYP
IN ('GEBAEUDE','RAEUME','FAKULTAET','LEHRGEBIET','MITARBEITER','KURSE'))
)
/
CREATE TABLE MARKUPUPDATE
(
  MARKUP_ID NUMBER NOT NULL,
  ARTIKEL_ID NUMBER NOT NULL,
  CONSTRAINT MARKUPUPDATE_PK PRIMARY KEY (MARKUP_ID,ARTIKEL_ID),
  CONSTRAINT MARKUPUPDATE_ARTIKEL_FK FOREIGN KEY (ARTIKEL_ID)
  REFERENCES ARTIKEL(ARTIKEL_ID),
  CONSTRAINT MARKUPUPDATE_MARKUP_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID)
)
/
CREATE TABLE GEBAEUDE
(
  GEBAEUDE_ID NUMBER NOT NULL,
  NAME VARCHAR(64),
  KUERZEL VARCHAR(8),
  POSTADRESSE VARCHAR(64),
  CONSTRAINT GEBAEUDE_PK PRIMARY KEY (GEBAEUDE_ID)
 )
/

CREATE TABLE RAEUME
(
  RAUM_ID NUMBER NOT NULL,
  NAME VARCHAR(64),
  GEBAEUDE_ID NUMBER,
  STOCKWERK CHAR(2),
  RAUMTYP VARCHAR(64),
  CONSTRAINT RAEUME_PK PRIMARY KEY (RAUM_ID),
  CONSTRAINT RAEUME_GEBAEUDE_FK FOREIGN KEY (GEBAEUDE_ID)
  REFERENCES GEBAEUDE(GEBAEUDE_ID)
 )
/
CREATE TABLE FAKULTAETEN
(
  FAKULTAET_ID NUMBER NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  CONSTRAINT FAKULTAET_PK PRIMARY KEY (FAKULTAET_ID)
 )
/
CREATE TABLE INSTITUTE
(
  INSTITUTS_ID NUMBER NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  FAKULTAET_ID NUMBER NOT NULL,
  CONSTRAINT INSTITUTS_PK PRIMARY KEY (INSTITUTS_ID),
  CONSTRAINT INST_FAK_FK FOREIGN KEY (FAKULTAET_ID) REFERENCES
  FAKULTAETEN(FAKULTAET_ID)
 )
/
CREATE TABLE LEHRGEBIETE
(
  LEHRGEBIET_ID NUMBER NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  FAKULTAET_ID NUMBER NOT NULL,
  INSTITUTS_ID NUMBER NULL,
  GEBAEUDE_ID NUMBER NOT NULL,
  LEITER NUMBER NOT NULL,
  CONSTRAINT LEHRGEBIET_PK PRIMARY KEY (LEHRGEBIET_ID),
  CONSTRAINT LEHRGEBIET_FAKULTAET_FK FOREIGN KEY(FAKULTAET_ID)
  REFERENCES FAKULTAETEN(FAKULTAET_ID),
  CONSTRAINT LEHRGEBIET_INST_FK FOREIGN KEY(INSTITUTS_ID)
  REFERENCES INSTITUTE(INSTITUTS_ID),
  CONSTRAINT LEHRGEBIET_GEBAEUDE_FK FOREIGN KEY(GEBAEUDE_ID)
  REFERENCES GEBAEUDE(GEBAEUDE_ID)
 )
/

CREATE TABLE MITARBEITER
(
  MITARBEITER_ID NUMBER NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  VNAME VARCHAR(64),
  TITEL VARCHAR(32),
  LEHRGEBIET_ID NUMBER NOT NULL,
  STATUS VARCHAR(32),
  TELEFON VARCHAR(64),
  EMAIL VARCHAR(64),
  RAUM_ID NUMBER null,
  CONSTRAINT MIT_PK PRIMARY KEY (MITARBEITER_ID),
  CONSTRAINT MIT_RAUM_FK FOREIGN KEY(RAUM_ID)
  REFERENCES RAEUME(RAUM_ID),
  CONSTRAINT MIT_LEHRGEBIET_FK FOREIGN KEY(LEHRGEBIET_ID)
  REFERENCES LEHRGEBIETE(LEHRGEBIET_ID)
 )
/
CREATE TABLE KURSE
(
  KURS_NR NUMBER NOT NULL,
  SEMESTER CHAR(12) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  BESCHREIBUNG VARCHAR(2056),
  LEHRGEBIET_ID NUMBER NOT NULL,
  KURS_SWS NUMBER  NULL,
  UEBUNGS_SWS NUMBER NULL,
  CONSTRAINT KURS_PK PRIMARY KEY (KURS_NR, SEMESTER),
  CONSTRAINT KURS_LEHRGEBIET_FK FOREIGN KEY(LEHRGEBIET_ID)
  REFERENCES LEHRGEBIETE(LEHRGEBIET_ID)
 )
/
CREATE TABLE GEBAEUDE_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  GEBAEUDE_ID NUMBER NOT NULL,
  FELDNAME VARCHAR(32),
  CONSTRAINT GEBAEUDE_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT GEBAEUDE_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT GEBAEUDE_MUPS_GEBAEUDE_FK FOREIGN KEY (GEBAEUDE_ID)
  REFERENCES GEBAEUDE(GEBAEUDE_ID),
  CONSTRAINT GEBAEUDE_MUPS_CK 
  CHECK (FELDNAME IN ('NAME','POSTADDRESSE','GEBAEUDETYP'))
 )
/
CREATE TABLE RAEUME_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  RAUM_ID NUMBER NOT NULL,
  FELDNAME VARCHAR(32),
  GEBAEUDE_ID NUMBER,
  STOCKWERK VARCHAR(32),
  TYP VARCHAR(64),
  CONSTRAINT RAEUME_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT RAEUME_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT RAEUME_MUPS_RAEUME_FK FOREIGN KEY (RAUM_ID)
  REFERENCES RAEUME(RAUM_ID),
  CONSTRAINT RAEUME_MUPS_CK 
  CHECK (FELDNAME IN ('NAME','GEBAEUDE_ID','STOCKWERK','RAUMTYP'))
 )
/
CREATE TABLE FAKULTAETEN_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  FAKULTAET_ID NUMBER NOT NULL,
  FELDNAME VARCHAR(64) NOT NULL,
  CONSTRAINT FAK_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT FAK_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT FAK_MUPS_FAK_FK FOREIGN KEY (FAKULTAET_ID)
  REFERENCES FAKULTAETEN(FAKULTAET_ID),
  CONSTRAINT FAK_MUPS_CK 
  CHECK (FELDNAME IN ('NAME'))
 )
/
CREATE TABLE LEHRGEBIETE_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  LEHRGEBIET_ID NUMBER NOT NULL,
  FELDNAME VARCHAR(64) NOT NULL,
  CONSTRAINT LGEB_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT LGEB_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT LGEB_MUPS_LEHRGEBIETE_FK FOREIGN KEY (LEHRGEBIET_ID)
  REFERENCES LEHRGEBIETE(LEHRGEBIET_ID),
  CONSTRAINT LGEB_MUPS_CK 
  CHECK (FELDNAME IN ('NAME','GEBAEUDE_ID'))
 )
/
CREATE TABLE MITARBEITER_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  MITARBEITER_ID NUMBER NOT NULL,
  FELDNAME VARCHAR(64) NOT NULL,
  CONSTRAINT MIT_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT MIT_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT MIT_MUPS_MIT_FK FOREIGN KEY (MITARBEITER_ID)
  REFERENCES MITARBEITER(MITARBEITER_ID),
  CONSTRAINT MIT_MUPS_CK 
  CHECK (FELDNAME IN
('NAME','VNAME','TITEL','LEHRGEBIET_ID','STATUS','TELEFON','EMAIL','RAUM_ID'))
 )
/
CREATE TABLE KURSE_MARKUPS
(
  MARKUP_ID NUMBER NOT NULL,
  KURS_NR NUMBER NOT NULL,
  SEMESTER CHAR(12) NOT NULL,
  FELDNAME VARCHAR(64) NOT NULL,
  CONSTRAINT KURSE_MUPS_PK PRIMARY KEY (MARKUP_ID),
  CONSTRAINT KURSE_MUPS_MUPS_FK FOREIGN KEY (MARKUP_ID)
  REFERENCES MARKUPS(MARKUP_ID),
  CONSTRAINT KURSE_MUPS_KURSE_FK FOREIGN KEY (KURS_NR,SEMESTER)
  REFERENCES KURSE(KURS_NR,SEMESTER),
  CONSTRAINT KURSE_MUPS_CK 
  CHECK (FELDNAME IN
('KURS_NR','SEMESTER','NAME','BESCHREIBUNG','KURSLEITER_ID'))
 )
/

ALTER TABLE LEHRGEBIETE 
ADD CONSTRAINT LEHRGEBIET_MITARBEITER_FK FOREIGN KEY(LEITER)
REFERENCES MITARBEITER(MITARBEITER_ID)
/

 CREATE SEQUENCE   "ARTIKELVERSION_SEQ"  MINVALUE 1 MAXVALUE
999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER 
NOCYCLE
/
 CREATE SEQUENCE   "ARTIKEL_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "BENUTZER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MEDIEN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "MENUBAUM_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "ROLLE_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/
 CREATE SEQUENCE   "SCHLAGWORT_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER  "BI_ARTIKEL" 
  before insert on "ARTIKEL"               
  for each row  
begin   
    select "ARTIKEL_SEQ".nextval into :NEW.ARTIKEL_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ARTIKEL" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ARTIKELVERSION" 
  before insert on "ARTIKELVERSION"               
  for each row  
begin   
    select "ARTIKELVERSION_SEQ".nextval into :NEW.ARTIKELVERSION_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ARTIKELVERSION" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_BENUTZER" 
  before insert on "BENUTZER"               
  for each row  
begin   
    select "BENUTZER_SEQ".nextval into :NEW.BENUTZER_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_BENUTZER" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MEDIEN" 
  before insert on "MEDIEN"               
  for each row  
begin   
    select "MEDIEN_SEQ".nextval into :NEW.MEDIEN_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MEDIEN" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_MENUBAUM" 
  before insert on "MENUBAUM"               
  for each row  
begin   
    select "MENUBAUM_SEQ".nextval into :NEW.MENUBAUM_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_MENUBAUM" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_ROLLE" 
  before insert on "ROLLE"               
  for each row  
begin   
    select "ROLLE_SEQ".nextval into :NEW.ROLLE_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_ROLLE" ENABLE
/
CREATE OR REPLACE TRIGGER  "BI_SCHLAGWORT" 
  before insert on "SCHLAGWORT"               
  for each row  
begin   
    select "SCHLAGWORT_SEQ".nextval into :NEW.SCHLAGWORT_ID from dual; 
end; 

/
ALTER TRIGGER  "BI_SCHLAGWORT" ENABLE
/
